version: '3'

services:
  api:
    image: node:14.15.4-alpine3.10
    command: yarn start
    depends_on: 
      postgres:
        condition: service_healthy
    ports:
      - "${PORT}:${PORT}"
    restart: "on-failure"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - POSTGRES_HOST=postgres

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_DB
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: "on-failure"
    healthcheck:
      test: ["CMD", "psql", "${POSTGRES_DB}", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-test:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - POSTGRES_PORT=${TEST_POSTGRES_PORT}
      - POSTGRES_DB=${TEST_POSTGRES_DB}
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
